# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrainter.xdc

# IP: ip/imageFrame2Read/imageFrame2Read.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageFrame2Read || ORIG_REF_NAME==imageFrame2Read} -quiet] -quiet

# IP: ip/imageFrame2/imageFrame2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageFrame2 || ORIG_REF_NAME==imageFrame2} -quiet] -quiet

# IP: ip/imageFrame1/imageFrame1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imageFrame1 || ORIG_REF_NAME==imageFrame1} -quiet] -quiet

# XDC: ip/imageFrame2Read/imageFrame2Read_ooc.xdc

# XDC: ip/imageFrame2/imageFrame2_ooc.xdc

# XDC: ip/imageFrame1/imageFrame1_ooc.xdc
